version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/npm"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"