# This is the default configuration file for local development. It connects to the integration backend.

include "application.local-base"

auth.domain="auth.tdr-integration.nationalarchives.gov.uk"

upload.url="https://upload.tdr-integration.nationalarchives.gov.uk"

consignmentapi.domain="https://api.tdr-integration.nationalarchives.gov.uk"

backendchecks.stepFunctionArn = ${?BACKEND_CHECKS_ARN}
metadatavalidation.stepFunctionArn = ${?DRAFT_METADATA_ARN}
export.stepFunctionArn = ${?EXPORT_ARN}