name: TDR Tag and pre deploy Transfer Frontend
on:
  push:
    branches:
      - master
permissions: {}
jobs:
  pre-deploy:
    permissions:
      contents: write
      id-token: write
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@e3622e3bbb9019981b3aaf6b278b2fce0c7d812b # v0.0.40
    with:
      java-version: '17'
      repo-name: tdr-transfer-frontend
      image-name: transfer-frontend
      build-command: |
        sbt dist
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      WIZ_PROJECT_ID: ${{ secrets.WIZ_PROJECT_TDR }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=$NEXT_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          NEXT_VERSION: ${{ needs.pre-deploy.outputs.next-version }}
