name: TDR Run Transfer Frontend tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
      - dependabot/**
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
    with:
      repo-name: tdr-transfer-frontend
      test-command: |
        npm --prefix npm ci
        npm --prefix npm run checks
        sbt scalafmtCheckAll test
      java-version: '17'
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
