name: TDR Run Transfer Frontend tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
      - dependabot/**
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@b6ba669dcee7fd4ac089c2e9fb234c48ddd93ab5 # v0.0.15
    with:
      repo-name: tdr-transfer-frontend
      test-command: |
        npm --prefix npm ci
        npm --prefix npm run checks
        sbt scalafmtCheckAll test
      java-version: '17'
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
